name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  actions: read

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            use_cross: false
            artifact: jartool-linux
          - target: x86_64-apple-darwin
            use_cross: true
            artifact: jartool-macos
          - target: x86_64-pc-windows-gnu
            use_cross: true
            artifact: jartool-windows.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install cross (for cross targets)
        if: matrix.use_cross == true
        run: cargo install cross

      - name: Build release binary
        run: |
          if [ "${{ matrix.use_cross }}" = "true" ]; then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Rename binary
        run: |
          if [ "${{ matrix.target }}" = "x86_64-pc-windows-gnu" ]; then
            mv target/${{ matrix.target }}/release/jartool.exe ${{ matrix.artifact }}
          else
            mv target/${{ matrix.target }}/release/jartool ${{ matrix.artifact }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
